### ISSUE TITLE
Placing Shulkers

### ISSUE THREAD

**Issue by OverCookedPancake** [henkelmax/advanced-shulkerboxes#1]
**Please read the [FAQ](https://modrepo.de/minecraft/shulkerbox/faq) before submitting a bug report!**

**Bug description**
Placing Shulker Boxes causes it to disappear, clicking the block where it should be shown the block outline and makes the open shulker sound but nothing happens after. Shift Placing the shulker does work as if nothing was wrong.

**Steps to reproduce the issue**
1. Get a shulker box
2. place it down
3. It wont show

**Expected behavior**
the shulker gets placed as normal (I think that is what the "expected behaviour" means)

**Log files**
where do I find this?

**Versions**
- Minecraft Version: 1.16.1
- Forge Version 1.16.1-forge-32.0.108
- Mod Version shulkerbox-1.16.1-1.0.1.jar

Youtube Link to a video of my problem
https://youtu.be/e-Z0K9sOwy0

Other Mods I am running in case that helps (idk anything about modding)
Abnormals-Core-1.16.1-2.0.2.jar
backpacked-1.5.1-1.16.1.jar
BiomesOPlenty-1.16.1-22.0.0.393-universal.jar
caelus-FORGE-1.16.1-2.0-beta7.jar
Clumps-6.0.0.3.jar
colytra-FORGE-1.16.1-4.0.0.1.jar
curios-FORGE-1.16.1-3.0.0.2.jar
Ma-Enchants-1.16.1-3.2.1.jar
OptiFine_1.16.1_HD_U_G2.jar
OptiForge-MC1.16.1-0.1.9.jar
shulkerbox-1.16.1-1.0.1.jar
The-Endergetic-Expansion-1.16.1-2.0.0.jar
undergarden-0.23.jar
Uppers-0.3.0.jar
Waystones_1.16.1-7.1.0.jar
Xaeros_Minimap_20.20.0_FORGE_1.16.1.jar

**Comment by henkelmax** [comment]
Does this issue occur without any other mods installed?

**Comment by OverCookedPancake** [comment]
> Does this issue occur without any other mods installed?

The issue changes with no other mods installed
It does the shulker place down sound and opens it as if you were to open it like with your mod. I also tried it with optifine and optiforge to see if those were messing with shulker rendering and it was the same result.

**Comment by henkelmax** [comment]
Alright. Can you narrow down the mod that causes the issue?

**Comment by OverCookedPancake** [comment]
The thing causing this other thing where placing the shulker down makes the place shulker sound and opens it up like with your mod is just because I was in creative mode. Also, it does not appear any other mods are causing the original bug

**Comment by henkelmax** [comment]
Unfortunately I am not able to reproduce this issue with just this mod installed.
Are you sure it doesn't work without these other mods?

**Comment by OverCookedPancake** [comment]
I don't think other mods are causing the issue. I've removed all other mods from the mods folder in .minecraft and created a new world and the issue persists. I might try redownloading the mod in case something went wrong when downloading.

**Comment by henkelmax** [comment]
So it works now?

**Comment by OverCookedPancake** [comment]
no, I was trying to see if downloading it again would fix it or if the problem was with the version of forge I am using but the issue only happens when using the mod

**Comment by henkelmax** [comment]
The shoulkerbox should just open without placing it down.
Can you send me your logfiles?
You can find them in your `.minecraft` folder in the logs directory.
The `debug.log` file is enough.

**Comment by OverCookedPancake** [comment]
https://gist.github.com/OverCookedPancake/5b4ce30f348ae473d672c379ca4d59dc

**Comment by OverCookedPancake** [comment]
ran the mod and did all the stuff with the issues in this https://gist.github.com/OverCookedPancake/5b4ce30f348ae473d672c379ca4d59dc

**Comment by henkelmax** [comment]
It seems that you are using an outdated version. 
Please update to the [latest version](https://www.curseforge.com/minecraft/mc-mods/advanced-shulkerboxes/files/3011806) and let me know if it works.

**Comment by OverCookedPancake** [comment]
Yup placing down with shift-click places it and just right-clicking works now both when a block is outlined and when not, works great thank you

**Comment by henkelmax** [comment]
No problem. Have fun!
