### ISSUE TITLE
Missing 1.20.1 version

### ISSUE THREAD

**Issue by MJRamon** [henkelmax/advanced-shulkerboxes#11]
### Bug description

Please add 1.20.1 version, the most used 1.20.x version in servers and modpacks. Thanks!

### Minecraft version

1.20.1

### Mod version

1.20.1

### Mod loader and version

1.20.1

### Steps to reproduce

Go to curseforge

### Log files

none

**Comment by henkelmax** [comment]
https://modrinth.com/mod/advanced-shulkerboxes/versions?g=1.20.1
