### ISSUE TITLE
Item Duping

### ISSUE THREAD

**Issue by OverCookedPancake** [henkelmax/advanced-shulkerboxes#2]
found another bug lol
**Bug description**
Item Duplication

**Steps to reproduce the issue**
Open shulker (the shulker was renamed if that helps)
take item from shulker
close shulker
open again and the item should be in the player inventory or where ever it was put and in the shulker as a duplicate (same enchantments same name same item like middle-clicking an item in creative mode)

**Expected behaviour**
item would be removed and put into player inventory like well... normal

**Log files**
https://gist.github.com/OverCookedPancake/7c5cec9a7103d3bff6b0c1efef67a2fd

**Versions**
- Minecraft version 1.16.1
- Forge version 1.16.1-forge-32.0.108
- Mod version shulkerbox-1.16.1-1.0.3.jar

**Other mods**
Abnormals-Core-1.16.1-2.0.2.jar
backpacked-1.5.1-1.16.1.jar
BiomesOPlenty-1.16.1-22.0.0.393-universal.jar
caelus-FORGE-1.16.1-2.0-beta7.jar
Clumps-6.0.0.3.jar
colytra-FORGE-1.16.1-4.0.0.1.jar
curios-FORGE-1.16.1-3.0.0.2.jar
Ma-Enchants-1.16.1-3.2.1.jar
OptiFine_1.16.1_HD_U_G2.jar
OptiForge-MC1.16.1-0.1.9.jar
shulkerbox-1.16.1-1.0.3.jar
The-Endergetic-Expansion-1.16.1-2.0.0.jar
undergarden-0.23.jar
Uppers-0.3.0.jar
Waystones_1.16.1-7.1.0.jar
Xaeros_Minimap_20.20.0_FORGE_1.16.1.jar

**Screenshots (Optional)**
https://youtu.be/aeLqEW1heME

**Comment by henkelmax** [comment]
Thanks for reporting this issue.
This time I am able to reproduce the issue.

**Comment by henkelmax** [comment]
I found the issue. It occurred only if you right-clicked the shulkerbox when facing a block.
Let me know if it works for you.

**Comment by OverCookedPancake** [comment]
works perfectly
