### ISSUE TITLE
*Actually* open from inventory (not toolbar)

### ISSUE THREAD

**Issue by DarkThor76** [henkelmax/advanced-shulkerboxes#4]
**Is your feature request related to a problem? Please describe.**
Having the shulker boxes in your character inventory means that upon death the shulker box will be lost. Having the ability to have a shulker box in an ender chest would keep it safe. Currently shulker boxes can not be opened from an ender chest or from your inventory. The shulker box must be in your _toolbar_.

**Describe the solution you'd like**
An option which allows shulker boxes to be opened from inventory or an ender chest.

**Describe alternatives you've considered**
This feature is available on other modpacks that run on Fabric, such as Tweakeroo.

**Additional context**
No other additional context necessary. Request should be self explanatory.

**Comment by henkelmax** [comment]
Unfortunately, due to restrictions how items/inventories are saved, this is not possible without completely rewriting this mod.
