### ISSUE TITLE
Crash on minecraft startup

### ISSUE THREAD

**Issue by zanecek** [henkelmax/advanced-shulkerboxes#5]
**Log files**
[shulk.log](https://github.com/henkelmax/advanced-shulkerboxes/files/6185381/shulk.log)

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.0
- Mod version: Shulkerbox-1.0.1 (1.0.0 works well)

**Other mods**
My privat modpack (100+ mods).

**Comment by henkelmax** [comment]
Thank you for reporting this issue!
