### ISSUE TITLE
Support for Tiered Shulkers

### ISSUE THREAD

**Issue by TheFantasticLoki** [henkelmax/advanced-shulkerboxes#7]
**Is your feature request related to a problem? Please describe.**
The latest version at the very least does not support Tiered Shulkers the successor to iron shulker boxes.

**Describe the solution you'd like**
Simply support opening tiered shulker boxes like you can normal shulker boxes.

**Describe alternatives you've considered**

**Additional context**

**Comment by henkelmax** [comment]
This mod is only meant for vanilla shulkerboxes.
Also see #3

**Comment by TheFantasticLoki** [comment]
make another mod then please.
