### ISSUE TITLE
Add compatibility for Carpet-AMS-Addition

### ISSUE THREAD

**Issue by sternschnaube** [henkelmax/advanced-shulkerboxes#8]
https://github.com/Minecraft-AMS/Carpet-AMS-Addition/blob/master/README_en.md

The mod offers a rule to double the Shulker Box inventory size, but it's not accessible.

**Comment by sternschnaube** [comment]
That's sad, but maybe you can look into Click Opener: https://github.com/RealMegaMinds/ClickOpener

He was adding support to access the bigger inventory. Maybe you can learn from his code.

Otherwise - thanks for the fast answer, then I need to find a better solution/mod for this case.

**Comment by henkelmax** [comment]
> He was adding support to access the bigger inventory. Maybe you can learn from his code.

I know how to add these features. It is just not a priority to add compatibility with that mod.
