### ISSUE TITLE
using 1.20.4-2.0.2 on forge causes crash

### ISSUE THREAD

**Issue by nickademas** [henkelmax/advanced-shulkerboxes#9]
### Bug description

game crashes 

### Minecraft version

1.20.4

### Mod version

1.20.4-2.0.2

### Mod loader and version

forge 49.0.27/ 49.0.14

### Steps to reproduce

1. Install this https://modrinth.com/mod/advanced-shulkerboxes/version/forge-1.20.4-2.0.2 and forge for 1.20.4
2. launch the game

### Log files

https://gist.github.com/nickademas/98cce24e74aba090740673fd25104395

### Screenshots

![obraz](https://github.com/henkelmax/advanced-shulkerboxes/assets/46594867/97147581-b61b-407d-ac03-a1c081aaa5e1)

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
